### ISSUE TITLE
add embark-theme to zathuraconf

### ISSUE THREAD

**Issue by gennaro-tedesco** [embark-theme/zathura#2]
Good evening! I maintain the project [zathuraconf](https://github.com/gennaro-tedesco/zathuraconf), a CLI to dynamically change zathura themes. I have noticed your port of embark theme for zathura and would like to ask if you would enjoy adding your theme there too.

It is as easy as copying-pasting your colours into a [json file](https://github.com/gennaro-tedesco/zathuraconf/blob/master/examples/solarized_dark.json) like in [these examples](https://github.com/gennaro-tedesco/zathuraconf/tree/master/examples). Or I could do myself, but I would ask you first (you probably know best what colours must go where)!

**Comment by skbolton** [comment]
Sweet! Let's collaborate on it. I am not a zathura user so I don't have anything set up. Looking at the highlights in the examples look pretty obvious other than the `page` highlight. What is that used for?

**Comment by gennaro-tedesco** [comment]
You can check what properties the definitions are used for [here](https://github.com/gennaro-tedesco/zathuraconf/blob/24606eb1d50d282b931f91563533312008019d06/cmd/config.go#L99-L126). As you can see, `page` is parsed into
```
- set completion-bg
- set inputbar-bg
- set recolor-lightcolor \"
- set index-bg
```
(I understand the names may be confusing :p)

**Comment by skbolton** [comment]
Sounds like you have a better hold of things than I do so feel free to do the first pass.

**Comment by gennaro-tedesco** [comment]
I have opened [this PR](https://github.com/gennaro-tedesco/zathuraconf/pull/6) with a sample configuration: it should look like the below:

<img width="579" alt="Screenshot 2022-10-16 at 16 56 03" src="https://user-images.githubusercontent.com/15387611/196042668-dc331bd4-cb06-4904-ba0b-2d0cde4871f7.png">
<img width="1280" alt="Screenshot 2022-10-16 at 16 57 13" src="https://user-images.githubusercontent.com/15387611/196042671-493adf61-52ba-4e52-b496-c80acb615755.png">

what do you think?

**Comment by skbolton** [comment]
I will leave feedback on your linked PR.
